[package]
name = "gst-plugin-custom-compositor"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
license = "MIT"
edition = "2018"
description = "Custom Compositor Plugin"
repository = "https://gstreamer.freedesktop.org"

[dependencies]
glib = "0.10"
gstreamer = { version = "0.16", features = ["v1_18"] }
gstreamer-base = { version = "0.16", features = ["v1_18"] }
gstreamer-video = { version = "0.16", features = ["v1_18"] }
once_cell = "1.0"

[lib]
name = "gstcustomcompositor"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper = "0.2"
